apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pv-claim
  namespace: test-csi-file-pv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi