apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: test.extension.example.com
spec:
  group: extension.example.com
  version: v1
  scope: Namespaced
  names:
    plural: test
    singular: test
    kind: test